//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail_nhap
    {
        public string id { get; set; }
        public string id_bill_nhap { get; set; }
        public string id_sp { get; set; }
        public int sl { get; set; }
        public string don_vi { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual bills_nhap bills_nhap { get; set; }
    }
}
