//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_detail_ban
    {
        public string id { get; set; }
        public string id_bill_ban { get; set; }
        public string listsanpham { get; set; }
        public string id_kh { get; set; }
        public Nullable<int> tongtien { get; set; }
    }
}
