//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills_ban
    {
        public string id { get; set; }
        public string id_kh { get; set; }
        public Nullable<System.DateTime> ngay_dat { get; set; }
        public Nullable<double> tong_tien { get; set; }
        public string trangthai { get; set; }
        public string ghichu { get; set; }
        public string ten_kh { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
    }
}
