//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class nha_cung_cap
    {
        public string id { get; set; }
        public string ten_ncc { get; set; }
        public string diachi_ncc { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
    }
}
