//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        public string id { get; set; }
        public string name { get; set; }
        public string id_loai_sp { get; set; }
        public string id_ncc { get; set; }
        public string mota_sp { get; set; }
        public Nullable<int> unit_price { get; set; }
        public int so_luong { get; set; }
        public string image { get; set; }
        public string don_vi_tinh { get; set; }
    
        public virtual loai_sp loai_sp { get; set; }
    }
}
